---
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - gem update --system
  - gem install bundler
cache: bundler
language: ruby
rvm:
  - 2.6.2
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
