default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rswag-example_development
test:
  <<: *default
  database: rswag-example_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

